# Generated by Django 2.1.7 on 2019-04-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetDumps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(unique=True)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('PRO', 'Processed')], default='PEN', max_length=2)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
