# Generated by Django 2.1.7 on 2019-04-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livetweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetdumps',
            name='path',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='tweetdumps',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('PRO', 'Processed')], default='PEN', max_length=50),
        ),
    ]
