# Generated by Django 2.1.7 on 2019-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livetweets', '0002_auto_20190427_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetCountSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
